version: "3"
services:
  fashionStore:
    image: fashionstore-0.0.1-SNAPSHOT.jar
    build:
      context: ./WebProgramming_Project
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  #  Create a service named db.
  db:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
    #   Give the container the name my_postgres. You can changes to something else.
    container_name: "project_eshop"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=karpos
      - POSTGRES_DB=FashionStore
    #   Maps port 5432 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5432:5432"
    #   Set a volume some that database is not lost after shutting down the container.
    #   I used the name postgres-data but you can changed it to something else.
    volumes:
      - postgres-data:/var/lib/postgresql/data
#volumes:
#  postgres-data:
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
